name: CD
on:
  create:
    tags:
      - v*
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: npm ci

      - run: npm run build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

#      - name: Run tests
#        run: npm run test
#
#      - name: Run visual regression tests
#        run: npm run test:integration
#
#      - name: Upload screenshots diffs
#        uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: screenshots
#          path: src/**/__diff_output__

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: public

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: ls -la && ls -la ./public

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: public

      - run: ls -la && ls -la ./public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
